package:
  name: kitchensink
  version: 0.3

source:
  git_url: git@github.com:hhuuggoo/kitchensink.git

requirements:
  build:
    - python

  run:
    - dill
    - rq
    - python
    - pandas
    - numpy
    - requests
    - flask
    - six
    - simpleservices
    - gevent
    - redis
about:
  home: https://github.com/ContinuumIO/ArrayManagement
  license: BSD
