package:
  name: rq
  version: !!str 0.4.6

source:
  fn: rq-0.4.6.tar.gz
  url: https://pypi.python.org/packages/source/r/rq/rq-0.4.6.tar.gz
  md5: 45a32d7281c010a6a1fb860823b3b652
#  patches:
   # List any patch files here
   # - fix.patch

build:
  preserve_egg_dir: True
  entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - rq = rq:main
    #
    # Would create an entry point called rq that calls rq.main()

    - rqworker=rq.scripts.rqworker:main
    - rqinfo=rq.scripts.rqinfo:main

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - redis-py

  run:
    - python
    - setuptools
    - redis-py

test:
  # Python imports
  imports:
    - rq
    - rq.compat
    - rq.contrib
    - rq.scripts

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    - rqworker --help
    - rqinfo --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/nvie/rq/
  license: BSD License
  summary: 'RQ is a simple, lightweight, library for creating background jobs, and processing them.'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
